import path from 'path'

import {loadConfig, PkgConfigOptions} from '@sanity/pkg-utils'

/**
 * Loads the `@sanity/pkg-utils` package.config file for the plugin in `basePath`.
 *
 * Works around `loadConfig` returning the config double-wrapped in a `default` property
 * when the target plugin is a CommonJS package (`"type": "commonjs"`), which is the case
 * for plugins generated by plugin-kit: the `export default` in package.config.ts is
 * transpiled to `module.exports.default`, and the ESM/CJS interop in `loadConfig` only
 * unwraps one level.
 */
export async function loadPackageConfig(options: {
  basePath: string
}): Promise<PkgConfigOptions | undefined> {
  const {basePath} = options
  const config = await loadConfig({cwd: basePath, pkgPath: path.join(basePath, 'package.json')})

  if (config && 'default' in config) {
    const unwrapped = (config as {default: unknown}).default
    if (unwrapped && typeof unwrapped === 'object') {
      return unwrapped as PkgConfigOptions
    }
  }

  return config
}
