packages:
  - dev/*
  - packages/*
  - packages/@repo/*
  - packages/@sanity/*
  - plugins/*
  - plugins/@sanity/*

catalog:
  '@sanity/client': ^7.13.1
  '@sanity/pkg-utils': ^10.1.1
  '@sanity/tsconfig': ^2.0.0
  '@sanity/vision': ^4.20.3
  '@types/node': ^24.10.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@typescript/native-preview': 7.0.0-dev.20251201.1
  eslint: ^9.39.1
  react: ^19.2.1
  react-dom: ^19.2.1
  sanity: ^4.20.3
  styled-components: ^6.1.19
  typescript: 5.9.3

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@oxfmt/*'
  - '@oxlint/*'
  - '@oxlint-tsgolint/*'
  - '@portabletext/*'
  - '@rollup/*'
  - '@sanity/*'
  - '@types/*'
  - '@typescript/*'
  - '@vite/*'
  - '@vitest/*'
  - csstype
  - eslint-plugin-oxlint
  - groq
  - groq-js
  - oxfmt
  - oxlint
  - oxlint-tsgolint
  - react
  - react-dom
  - react-is
  - rollup
  - sanity
  - vite
  - vitest

overrides:
  styled-components: npm:@sanity/styled-components@latest

patchedDependencies:
  '@bynder/compact-view': patches/@bynder__compact-view.patch

trustPolicy: no-downgrade

trustPolicyExclude:
  - '@octokit/endpoint@9.0.6'
  - '@octokit/plugin-paginate-rest@9.2.2'
  - '@sanity/sdk@2.1.2'
  - chokidar@4.0.3
  - groq@3.88.1-typegen-experimental.0
  - reselect@5.1.1
  - rxjs@7.8.2
  - semver@5.7.2 || 6.3.1
  - undici@5.29.0
  - vite@6.4.1
