packages:
  - dev/*
  - packages/*
  - packages/@repo/*
  - packages/@sanity/*
  - plugins/*
  - plugins/@sanity/*

catalog:
  '@sanity/client': 7.14.0
  '@sanity/pkg-utils': ^10.3.3
  '@sanity/tsconfig': ^2.1.0
  '@sanity/ui': ^3.1.11
  '@sanity/vision': ^5.5.0
  '@types/node': ^24.10.9
  '@types/react': ^19.2.9
  '@types/react-dom': ^19.2.3
  '@typescript/native-preview': 7.0.0-dev.20260122.4
  babel-plugin-react-compiler: ^1.0.0
  babel-plugin-styled-components: ^2.1.4
  eslint: ^9.39.2
  react: ^19.2.3
  react-dom: ^19.2.3
  rxjs: ^7.8.2
  sanity: ^5.5.0
  styled-components: ^6.3.8
  typescript: 5.9.3

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@oxfmt/*'
  - '@oxlint/*'
  - '@oxlint-tsgolint/*'
  - '@portabletext/*'
  - '@rollup/*'
  - '@sanity/*'
  - '@types/*'
  - '@typescript/*'
  - '@vite/*'
  - '@vitest/*'
  - csstype
  - eslint-plugin-oxlint
  - groq
  - groq-js
  - oxfmt
  - oxlint
  - oxlint-tsgolint
  - react
  - react-dom
  - react-is
  - rollup
  - sanity
  - vite
  - vitest
  # Renovate security update: lodash-es@4.17.23
  - lodash-es@4.17.23

overrides:
  styled-components: npm:@sanity/styled-components@latest

patchedDependencies:
  '@bynder/compact-view': patches/@bynder__compact-view.patch

trustPolicy: no-downgrade

trustPolicyExclude:
  - '@octokit/endpoint@9.0.6'
  - '@octokit/plugin-paginate-rest@9.2.2'
  - '@sanity/sdk@2.1.2'
  - chokidar@4.0.3
  - groq@3.88.1-typegen-experimental.0
  - react-redux@8.1.3 || 9.2.0
  - reselect@5.1.1
  - rxjs@7.8.2
  - semver@5.7.2 || 6.3.1
  - ts-api-utils@2.3.0
  - undici@5.29.0
  - vite@6.4.1
