packages:
  - packages/*
  - packages/@repo/*
  - packages/@sanity/*

catalog:
  '@sanity/pkg-utils': ^9.1.1
  '@types/react': ^19.2.6
  react: ^19.2.0
  sanity: ^4.16.0
  typescript: 5.9.3

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@oxfmt/*'
  - '@oxlint/*'
  - '@oxlint-tsgolint/*'
  - '@portabletext/*'
  - '@rollup/*'
  - '@sanity/*'
  - '@types/*'
  - '@typescript/*'
  - '@vite/*'
  - '@vitest/*'
  - csstype
  - groq
  - oxfmt
  - oxlint
  - oxlint-tsgolint
  - rollup
  - sanity
  - vite
  - vitest

trustPolicy: no-downgrade

trustPolicyExclude:
  - '@octokit/endpoint@9.0.6'
  - '@octokit/plugin-paginate-rest@9.2.2'
  - '@sanity/sdk@2.1.2'
  - chokidar@4.0.3
  - groq@3.88.1-typegen-experimental.0
  - reselect@5.1.1
  - rxjs@7.8.2
  - semver@5.7.2 || 6.3.1
  - undici@5.29.0
  - vite@6.4.1
