/**
 * Prints the compatibility matrix quoted in README.md. Run it with `pnpm report`.
 */
import {match as matchV6} from 'path-to-regexp-v6'
import {match as matchV8} from 'path-to-regexp-v8'

import {type CorpusEntry, V6_CORPUS, V8_CORPUS} from './corpus.ts'
import {createRouteMatcher, type RouteMatch} from './matchRoute.ts'
import {urlPatternImplementation} from './urlPattern.ts'

const NO_MATCH = '—'

function write(line = ''): void {
  process.stdout.write(`${line}\n`)
}

function code(value: string): string {
  return `\`${value.replaceAll('|', '\\|')}\``
}

function formatParams(params: Record<string, string | string[]> | undefined): string {
  if (!params) return NO_MATCH
  const entries = Object.entries(params)
  if (entries.length === 0) return '`{}`'
  return code(`{${entries.map(([key, value]) => `${key}: ${JSON.stringify(value)}`).join(', ')}}`)
}

type Params = Record<string, string | string[]>
type MatchFunction = (pathname: string) => false | {params: Params}
type Outcome = {ok: false} | {ok: true; params?: Params}

function runPathToRegexp(compile: () => MatchFunction, pathname: string): Outcome {
  let matcher: MatchFunction
  try {
    matcher = compile()
  } catch {
    return {ok: false}
  }
  const result = matcher(pathname)
  return {ok: true, params: result ? result.params : undefined}
}

function runMatcher(pattern: string, pathname: string): RouteMatch | undefined | 'throws' {
  try {
    return createRouteMatcher(pattern)(pathname)
  } catch {
    return 'throws'
  }
}

function compileStatus(pattern: string): {v6: boolean; v8: boolean; matcher: boolean} {
  const compiles = (run: () => unknown): boolean => {
    try {
      run()
      return true
    } catch {
      return false
    }
  }
  return {
    v6: compiles(() => matchV6(pattern)),
    v8: compiles(() => matchV8(pattern)),
    matcher: compiles(() => createRouteMatcher(pattern)),
  }
}

function writeCompileTable(title: string, corpus: CorpusEntry[]): void {
  write(`### ${title}`)
  write()
  write('| Pattern | path-to-regexp v6 | path-to-regexp v8 | URLPattern matcher |')
  write('| --- | --- | --- | --- |')
  for (const {pattern} of corpus) {
    const status = compileStatus(pattern)
    const cell = (ok: boolean): string => (ok ? 'compiles' : '**throws**')
    write(
      `| ${code(pattern)} | ${cell(status.v6)} | ${cell(status.v8)} | ${cell(status.matcher)} |`,
    )
  }
  write()
}

function writeMatchTable(title: string, corpus: CorpusEntry[]): void {
  write(`### ${title}`)
  write()
  write('| Pattern | Pathname | path-to-regexp v6 | path-to-regexp v8 | URLPattern matcher |')
  write('| --- | --- | --- | --- | --- |')
  for (const {pattern, inputs} of corpus) {
    for (const input of inputs) {
      const decode = decodeURIComponent
      const v6 = runPathToRegexp(() => matchV6<Params>(pattern, {decode}), input)
      const v8 = runPathToRegexp(() => matchV8<Params>(pattern, {decode}), input)
      const matched = runMatcher(pattern, input)
      const cell = (result: Outcome): string =>
        result.ok ? formatParams(result.params) : '_throws_'
      write(
        `| ${code(pattern)} | ${code(input)} | ${cell(v6)} | ${cell(v8)} | ${
          matched === 'throws' ? '_throws_' : formatParams(matched?.params)
        } |`,
      )
    }
  }
  write()
}

write(
  `<!-- Generated by \`pnpm report\` on ${urlPatternImplementation} URLPattern, ${process.version} -->`,
)
write()
write('## Which patterns compile')
write()
writeCompileTable('Patterns written for path-to-regexp v6', V6_CORPUS)
writeCompileTable('Patterns written for path-to-regexp v8', V8_CORPUS)
write('## What they match')
write()
writeMatchTable('Patterns written for path-to-regexp v6', V6_CORPUS)
writeMatchTable('Patterns written for path-to-regexp v8', V8_CORPUS)
