/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Rendition = {
  publicuri?: string
}

export type SanityVercelProtectionBypass = {
  _id: string
  _type: 'sanity.vercelProtectionBypass'
  _createdAt: string
  _updatedAt: string
  _rev: string
  secret?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type UnsplashPost = {
  _id: string
  _type: 'unsplashPost'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type SanityPreviewUrlSecret = {
  _id: string
  _type: 'sanity.previewUrlSecret'
  _createdAt: string
  _updatedAt: string
  _rev: string
  secret?: string
  source?: string
  studioUrl?: string
  userId?: string
}

export type MarkdownTest = {
  _id: string
  _type: 'markdownTest'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  markdown?: Markdown
}

export type Markdown = string

export type ColorTest = {
  _id: string
  _type: 'colorTest'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  testColor1?: Color
  testColor2?: Color
  testColor3?: Color
  colorList?: Array<
    {
      _key: string
    } & Color
  >
  readOnlyColor?: Color
  colorGrid?: Array<
    {
      _key: string
    } & Color
  >
  objectWithObjectWithColors?: {
    objectWithColors?: {
      primaryColor?: Color
      secondaryColor?: Color
      extraColor?: Color
    }
  }
}

export type Color = {
  _type: 'color'
  hex?: string
  alpha?: number
  hsl?: HslaColor
  hsv?: HsvaColor
  rgb?: RgbaColor
}

export type RgbaColor = {
  _type: 'rgbaColor'
  r?: number
  g?: number
  b?: number
  a?: number
}

export type HsvaColor = {
  _type: 'hsvaColor'
  h?: number
  s?: number
  v?: number
  a?: number
}

export type HslaColor = {
  _type: 'hslaColor'
  h?: number
  s?: number
  l?: number
  a?: number
}

export type BynderTest = {
  _id: string
  _type: 'bynderTest'
  _createdAt: string
  _updatedAt: string
  _rev: string
  Title?: string
  image1?: BynderAsset
  image2?: BynderAsset
}

export type BynderAsset = {
  _type: 'bynder.asset'
  id?: string
  name?: string
  databaseId?: string
  type?: string
  previewUrl?: string
  previewImg?: string
  datUrl?: string
  description?: string
  aspectRatio?: number
  width?: number
  height?: number
  videoUrl?: string
  selectedUrl?: string
}

export type AprimoTest = {
  _id: string
  _type: 'aprimoTest'
  _createdAt: string
  _updatedAt: string
  _rev: string
  Title?: string
  aprimoCDNImage?: AprimoCdnasset
  assetArray?: Array<
    {
      _key: string
    } & AprimoCdnasset
  >
}

export type AprimoCdnasset = {
  _type: 'aprimo.cdnasset'
  id?: string
  title?: string
  rendition?: Rendition
}

export type AprimoAsset = {
  _type: 'aprimo.asset'
  id?: string
  title?: string
  additionalFile?: AprimoAdditionalFile
}

export type AprimoAdditionalFile = {
  _type: 'aprimo.additionalFile'
  additionalFileId?: string
  fileName?: string
  label?: string
  type?: string
}

export type CodeTest = {
  _id: string
  _type: 'codeTest'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  basicCode?: Code
  codeWithOptions?: Code
  readOnlyCode?: Code
  codeList?: Array<
    {
      _key: string
    } & Code
  >
}

export type Code = {
  _type: 'code'
  language?: string
  filename?: string
  code?: string
  highlightedLines?: Array<number>
}

export type RichDateTest = {
  _id: string
  _type: 'richDateTest'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  scheduledAt?: RichDate
  publishedAt?: RichDate
  dateList?: Array<
    {
      _key: string
    } & RichDate
  >
}

export type RichDate = {
  _type: 'richDate'
  local?: string
  utc?: string
  timezone?: string
  offset?: number
}

export type I18nArrayCircularSchemaRepro = {
  _id: string
  _type: 'i18nArrayCircularSchemaRepro'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  body?: I18nArrayCircularBodyContent
}

export type I18nArrayCircularBodyContent = Array<{
  tabs?: Array<{
    body?: I18nArrayCircularBodyContent
    _type: 'tab'
    _key: string
  }>
  _type: 'tabs'
  _key: string
}>

export type I18nArrayPerformanceTest = {
  _id: string
  _type: 'i18nArrayPerformanceTest'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: InternationalizedArrayString
  age?: number
  field_0?: InternationalizedArrayString
  field_1?: InternationalizedArrayString
  field_2?: InternationalizedArrayString
  field_3?: InternationalizedArrayString
  field_4?: InternationalizedArrayString
  field_5?: InternationalizedArrayString
  field_6?: InternationalizedArrayString
  field_7?: InternationalizedArrayString
  field_8?: InternationalizedArrayString
  field_9?: InternationalizedArrayString
  field_10?: InternationalizedArrayString
  field_11?: InternationalizedArrayString
  field_12?: InternationalizedArrayString
  field_13?: InternationalizedArrayString
  field_14?: InternationalizedArrayString
  field_15?: InternationalizedArrayString
  field_16?: InternationalizedArrayString
  field_17?: InternationalizedArrayString
  field_18?: InternationalizedArrayString
  field_19?: InternationalizedArrayString
  field_20?: InternationalizedArrayString
  field_21?: InternationalizedArrayString
  field_22?: InternationalizedArrayString
  field_23?: InternationalizedArrayString
  field_24?: InternationalizedArrayString
  field_25?: InternationalizedArrayString
  field_26?: InternationalizedArrayString
  field_27?: InternationalizedArrayString
  field_28?: InternationalizedArrayString
  field_29?: InternationalizedArrayString
}

export type InternationalizedArrayString = Array<
  {
    _key: string
  } & InternationalizedArrayStringValue
>

export type InternationalizedPost = {
  _id: string
  _type: 'internationalizedPost'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: InternationalizedArrayString
  description?: InternationalizedArrayText
  slug?: Slug
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type InternationalizedArrayText = Array<
  {
    _key: string
  } & InternationalizedArrayTextValue
>

export type InternationalizedArrayTextValue = {
  _type: 'internationalizedArrayTextValue'
  value?: string
  language: string
}

export type InternationalizedArrayStringValue = {
  _type: 'internationalizedArrayStringValue'
  value?: string
  language: string
}

export type TranslationMetadata = {
  _id: string
  _type: 'translation.metadata'
  _createdAt: string
  _updatedAt: string
  _rev: string
  translations?: InternationalizedArrayReference
  schemaTypes?: Array<string>
}

export type InternationalizedArrayReference = Array<
  {
    _key: string
  } & InternationalizedArrayReferenceValue
>

export type LessonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'lesson'
}

export type InternationalizedArrayReferenceValue = {
  _type: 'internationalizedArrayReferenceValue'
  value?: LessonReference
  language: string
}

export type Lesson = {
  _id: string
  _type: 'lesson'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  language?: string
  content?: string
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Rendition
  | SanityVercelProtectionBypass
  | SanityImageAssetReference
  | UnsplashPost
  | SanityImageCrop
  | SanityImageHotspot
  | SanityPreviewUrlSecret
  | MarkdownTest
  | Markdown
  | ColorTest
  | Color
  | RgbaColor
  | HsvaColor
  | HslaColor
  | BynderTest
  | BynderAsset
  | AprimoTest
  | AprimoCdnasset
  | AprimoAsset
  | AprimoAdditionalFile
  | CodeTest
  | Code
  | RichDateTest
  | RichDate
  | I18nArrayCircularSchemaRepro
  | I18nArrayCircularBodyContent
  | I18nArrayPerformanceTest
  | InternationalizedArrayString
  | InternationalizedPost
  | Slug
  | InternationalizedArrayText
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | TranslationMetadata
  | InternationalizedArrayReference
  | LessonReference
  | InternationalizedArrayReferenceValue
  | Lesson
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol
