/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Rendition = {
  publicuri?: string
}

export type SanityVercelProtectionBypass = {
  _id: string
  _type: 'sanity.vercelProtectionBypass'
  _createdAt: string
  _updatedAt: string
  _rev: string
  secret?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type UnsplashPost = {
  _id: string
  _type: 'unsplashPost'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityPreviewUrlSecret = {
  _id: string
  _type: 'sanity.previewUrlSecret'
  _createdAt: string
  _updatedAt: string
  _rev: string
  secret?: string
  source?: string
  studioUrl?: string
  userId?: string
}

export type MarkdownTest = {
  _id: string
  _type: 'markdownTest'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  markdown?: Markdown
}

export type Markdown = string

export type ColorTest = {
  _id: string
  _type: 'colorTest'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  testColor1?: Color
  testColor2?: Color
  testColor3?: Color
  colorList?: Array<
    {
      _key: string
    } & Color
  >
  readOnlyColor?: Color
  colorGrid?: Array<
    {
      _key: string
    } & Color
  >
  objectWithObjectWithColors?: {
    objectWithColors?: {
      primaryColor?: Color
      secondaryColor?: Color
      extraColor?: Color
    }
  }
}

export type Color = {
  _type: 'color'
  hex?: string
  alpha?: number
  hsl?: HslaColor
  hsv?: HsvaColor
  rgb?: RgbaColor
}

export type RgbaColor = {
  _type: 'rgbaColor'
  r?: number
  g?: number
  b?: number
  a?: number
}

export type HsvaColor = {
  _type: 'hsvaColor'
  h?: number
  s?: number
  v?: number
  a?: number
}

export type HslaColor = {
  _type: 'hslaColor'
  h?: number
  s?: number
  l?: number
  a?: number
}

export type BynderTest = {
  _id: string
  _type: 'bynderTest'
  _createdAt: string
  _updatedAt: string
  _rev: string
  Title?: string
  image1?: BynderAsset
  image2?: BynderAsset
}

export type BynderAsset = {
  _type: 'bynder.asset'
  id?: string
  name?: string
  databaseId?: string
  type?: string
  previewUrl?: string
  previewImg?: string
  datUrl?: string
  description?: string
  aspectRatio?: number
  width?: number
  height?: number
  videoUrl?: string
  selectedUrl?: string
}

export type AprimoTest = {
  _id: string
  _type: 'aprimoTest'
  _createdAt: string
  _updatedAt: string
  _rev: string
  Title?: string
  aprimoCDNImage?: AprimoCdnasset
  assetArray?: Array<
    {
      _key: string
    } & AprimoCdnasset
  >
}

export type AprimoCdnasset = {
  _type: 'aprimo.cdnasset'
  id?: string
  title?: string
  rendition?: Rendition
}

export type AprimoAsset = {
  _type: 'aprimo.asset'
  id?: string
  title?: string
  additionalFile?: AprimoAdditionalFile
}

export type AprimoAdditionalFile = {
  _type: 'aprimo.additionalFile'
  additionalFileId?: string
  fileName?: string
  label?: string
  type?: string
}

export type CodeTest = {
  _id: string
  _type: 'codeTest'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  basicCode?: Code
  codeWithOptions?: Code
  readOnlyCode?: Code
  codeList?: Array<
    {
      _key: string
    } & Code
  >
}

export type Code = {
  _type: 'code'
  language?: string
  filename?: string
  code?: string
  highlightedLines?: Array<number>
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type AllSanitySchemaTypes =
  | Rendition
  | SanityVercelProtectionBypass
  | SanityImageAssetReference
  | UnsplashPost
  | SanityImageCrop
  | SanityImageHotspot
  | SanityPreviewUrlSecret
  | MarkdownTest
  | Markdown
  | ColorTest
  | Color
  | RgbaColor
  | HsvaColor
  | HslaColor
  | BynderTest
  | BynderAsset
  | AprimoTest
  | AprimoCdnasset
  | AprimoAsset
  | AprimoAdditionalFile
  | CodeTest
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug

export declare const internalGroqTypeReferenceTo: unique symbol
