import {definePlugin, defineType} from 'sanity'
import {muxInput} from 'sanity-plugin-mux-input'

const muxTrailer = defineType({
  type: 'document',
  name: 'muxTrailer',
  title: 'Trailer (Mux)',
  fields: [
    {type: 'string', name: 'title', title: 'Title'},
    {type: 'mux.video', name: 'video', title: 'Video'},
  ],
})

export const muxInputExample = definePlugin(() => ({
  schema: {types: [muxTrailer]},
  plugins: [
    muxInput({
      // Make the studio tool clearly attributable to the plugin in the nav.
      tool: {title: 'mux-input: Videos'},
      video_quality: 'plus',
      max_resolution_tier: '2160p',
      static_renditions: ['highest'],
      defaultAutogeneratedSubtitleLang: 'en',
    }),
  ],
}))
