name: TypeGen

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: pnpm build --filter=test-studio^...
      - run: pnpm typegen
      - uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          client-id: ${{ secrets.ECOSPARK_CLIENT_ID }}
          private-key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        id: pr
        with:
          body: I ran `pnpm typegen` 🧑‍💻
          branch: actions/typegen/${{ github.ref_name }}
          commit-message: 'fix(typegen): 🤖 ✨'
          labels: 🤖 bot
          sign-commits: true
          title: 'fix(typegen): 🤖 ✨'
          token: ${{ steps.generate-token.outputs.token }}
      - name: Enable automerge on Pull Request
        if: steps.pr.outputs.pull-request-operation == 'created'
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          PR_NUMBER: ${{ steps.pr.outputs.pull-request-number }}
        run: gh pr merge --squash --auto "$PR_NUMBER"
